/*
 * File: app/model/User.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Info.model.User', {
    extend: 'Ext.data.Model',

    config: {
        fields: [
            {
                name: 'name'
            },
            {
                name: 'password'
            },
            {
                name: 'disabled'
            },
            {
                name: 'email'
            },
            {
                name: 'url'
            },
            {
                name: 'date'
            },
            {
                name: 'number'
            },
            {
                name: 'height'
            },
            {
                name: 'enable'
            },
            {
                name: 'cool'
            },
            {
                name: 'color'
            },
            {
                name: 'team'
            },
            {
                name: 'secret'
            },
            {
                name: 'spinner'
            },
            {
                name: 'bio'
            }
        ]
    }
});