/*
 * File: app/view/NumbersPicker.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.NumbersPicker', {
    extend: 'Ext.picker.Picker',
    alias: 'widget.numbersPicker',

    config: {
        useTitles: true,
        slots: [
            {
                xtype: 'pickerslot',
                data: [
                    {
                        text: 'One',
                        value: 1
                    },
                    {
                        text: 'Two',
                        value: 2
                    },
                    {
                        text: 'Three',
                        value: 3
                    }
                ],
                name: 'number1',
                title: 'Number 1'
            },
            {
                xtype: 'pickerslot',
                data: [
                    {
                        text: 'One',
                        value: 1
                    },
                    {
                        text: 'Two',
                        value: 2
                    },
                    {
                        text: 'Three',
                        value: 3
                    }
                ],
                name: 'number2',
                title: 'Number 2'
            }
        ]
    }

});