/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.Loader.setConfig({
    enabled: true
});

Ext.application({
    stores: [
        'TweetStore'
    ],
    views: [
        'TweetList'
    ],
    name: 'Tweets',

    launch: function() {
        Ext.util.Format.timeAgoInWords = function(date) {
            try {
                var now = Math.ceil(Number(new Date()) / 1000),
                    dateTime = Math.ceil(Number(new Date(date)) / 1000),
                    diff = now - dateTime,
                    str;

                if (diff < 60) {
                    return String(diff) + ' seconds ago';
                } else if (diff < 3600) {
                    str = String(Math.ceil(diff / (60)));
                    return str + (str == "1" ? ' minute' : ' minutes') + ' ago';
                } else if (diff < 86400) {
                    str = String(Math.ceil(diff / (3600)));
                    return str + (str == "1" ? ' hour' : ' hours') + ' ago';
                } else if (diff < 60 * 60 * 24 * 365) {
                    str = String(Math.ceil(diff / (60 * 60 * 24)));
                    return str + (str == "1" ? ' day' : ' days') + ' ago';
                } else {
                    return Ext.Date.format(new Date(date), 'jS M \'y');
                }
            } catch (e) {
                return '';
            }
        };
        Ext.getStore('TweetStore').load();
        if (Ext.os.is.Phone) {
            Ext.create('Tweets.view.TweetList', {
                fullscreen: true
            });
        } else {
            Ext.Viewport.add({
                xclass: 'Tweets.view.TweetList',
                width: 380,
                height: 420,
                centered: true,
                modal: true,
                hideOnMaskTap: false
            }).show();
        }

    }

});
