/*
 * File: app/view/Step3Panel.js
 *
 * This file was generated by Sencha Architect version 2.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.Step3Panel', {
    extend: 'Ext.form.Panel',
    alias: 'widget.step3',

    config: {
        items: [
            {
                xtype: 'fieldset',
                title: 'Choose an operation',
                items: [
                    {
                        xtype: 'radiofield',
                        label: 'Add',
                        name: 'operation',
                        value: 'add',
                        checked: true
                    },
                    {
                        xtype: 'radiofield',
                        label: 'Subtract',
                        name: 'operation',
                        value: 'subtract'
                    },
                    {
                        xtype: 'radiofield',
                        label: 'Multiply',
                        name: 'operation',
                        value: 'multiply'
                    },
                    {
                        xtype: 'radiofield',
                        label: 'Divide',
                        name: 'operation',
                        value: 'divide'
                    }
                ]
            },
            {
                xtype: 'button',
                ui: 'confirm',
                text: 'Calculate!'
            }
        ]
    }

});